<?php $this->load->view('includes/navbar'); 
date_default_timezone_set('Asia/Manila');

?>

<!--=========================================
=            Mobile Only Section            =
==========================================-->


<div class="row hide-on-large-only">

	
	<center style="margin-top: 5%;">
		<img src="<?=base_url()?>assets/img/feu-seal.png" style="width: 20%;" alt="">
		<h5>Learning Management and Monitoring System - Correl</h5>
	</center>
	<!--=======================================
	=            Features - Mobile            =
	========================================-->
	
<!--==============================
=            Features            =
===============================-->

<div class="row" id="">
	<div class="row">
		<center><i class="material-icons small color-primary-green">clear_all</i></center>
		<h4 class="center a-roboto-cond">Features</h4>
	</div>
	<div class="row">
		<div class="col s12">
			<div class="col s12">	
				<center>
					<img src="<?=base_url()?>assets/img/icons/learning.svg" class="a-icons-landing" alt="">
					<h5 class="a-icons-header center a-nikki1">Learn Online</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					E-Rev has an online learning management system that gets you the training you need. Because it's online, delivered over the web, you can proceed at your own pace, anytime, anywhere, and on any device.
				</p>
			</div>	
			<div class="col s12">
				<center>
					<img src="<?=base_url()?>assets/img/icons/personalized.svg" class="a-icons-landing" alt="">
					<h5 class="a-icons-header center a-nikki1">Personalized Experience</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					Simulate a personalization engine by manually combing and interpreting the data from your learning management system (LMS) reports and making recommendations to your learning students.
				</p>
			</div>
			<div class="col s12">
				<center>
					<img src="<?=base_url()?>assets/img/icons/analytics.svg" class="a-icons-landing" alt="">
					<h5 class="a-icons-header center a-nikki1">Grades Analysis</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					Online grade assessment is a powerful method to engage students, encourage learning and test student understanding of subject content. The LMS offers a wide variety of features to support an assessment of students.
				</p>
			</div>
			<div class="col s12">
				<center>
					<img src="<?=base_url()?>assets/img/icons/monitor.svg" class="a-icons-landing" alt="">
					<h5 class="a-icons-header center a-nikki1">Lecturer Monitoring</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					The timekeeping system will monitor the lecturer’s attendance. The time in and time out of lecturers will be recorded via the biometric scanner. The total number of hours rendered by the lecturers will be computed and generated by the system.
				</p>. 
			</div>
		</div>
	</div>
</div>

<!--====  End of Features  ====-->


<!--====  End of Features - Mobile  ====-->

	<!--=============================================
	=            What you'll get section            =
	==============================================-->
	
	<div class="row">
		<center><i class="material-icons small color-primary-green">clear_all</i></center>
		<h4 class="center a-roboto-cond" style="text-transform: uppercase;">What you'll get as a student</h4>
		<div class="row valign-wrapper">
			<div class="col s6">
				<center>
					<img src="<?=base_url()?>assets/img/icons/tailored.svg " style="width: 50%;">
				</center>
			</div>
			<div class="col s6">
				<h5 style="text-transform: capitalize;">Tailored experience, especially made for your needs</h5>
				<p>Eiusmod ea occaecat do esse adipisicing irure culpa cillum do sit pariatur veniam esse aute officia sit deserunt officia sint deserunt mollit veniam elit labore enim dolor et in proident irure ea sint dolor occaecat ex aliqua eiusmod irure.</p>
			</div>
		</div>
		<div class="row valign-wrapper">
			<div class="col s6">
				<h5 style="text-transform: capitalize;">enhance your skills and knowledge</h5>
				<p>Eiusmod ea occaecat do esse adipisicing irure culpa cillum do sit pariatur veniam esse aute officia sit deserunt officia sint deserunt mollit veniam elit labore enim dolor et in proident irure ea sint dolor occaecat ex aliqua eiusmod irure.</p>
			</div>
			<div class="col s6">
				<center>
					<img src="<?=base_url()?>assets/img/icons/brain.svg " style="width: 50%;">
				</center>
			</div>
		</div>
		<div class="row valign-wrapper">
			<div class="col s6">
				<center>
					<img src="<?=base_url()?>assets/img/icons/megaphone.svg " style="width: 50%;">
				</center>
			</div>
			<div class="col s6">
				<h5 style="text-transform: capitalize;">Increase communication</h5>
				<p>Eiusmod ea occaecat do esse adipisicing irure culpa cillum do sit pariatur veniam esse aute officia sit deserunt officia sint deserunt mollit veniam elit labore enim dolor et in proident irure ea sint dolor occaecat ex aliqua eiusmod irure.</p>
			</div>
		</div>
	</div>

	
	<!--====  End of What you'll get section  ====-->

	<!--=======================================
	=            Engineers Section            =
	========================================-->
	
	
	<div class="row">
		<div class="col s2"></div>
		<div class="col s8 ">
			<h4>
				<center>
					<i class="material-icons small color-primary-green">clear_all</i>
					<p style="text-transform: uppercase;">FEU - Tech engineering students</p>
				</center>
			</h4>
			<!-- Hisham -->
			<div class="row">
				<div class="row ">
					<center>
						<img  class="circle responsive-img" style="width: 100px;
						height: 100px; object-fit: cover;" src="<?=base_url()?>assets/img/profiles/profile.jpg" >

					</center>
				</div>
				<div class="row" style="text-align: justify;">
					<h5 class="">Engr. Hisham Sacar</h5>
					<blockquote class="color-primary-green">
						<h5 class="color-black">1st Placer 2017 CE Board Exam</h5>
					</blockquote>
					<p>Hisham, 21, a graduate from Quirino High School, emerged No. 1 among the 2,514 board passers nationwide. His excellent academic performance has enabled him to get a full-academic scholarship from FEU Tech. </p>
					<a href="www.feutech.edu.ph"><i> - https://www.feutech.edu.ph</i></a>
				</div>
			</div>
			<!-- David Flores -->
			<div class="row">
				<div class="row ">
					<center>
						<img  class="circle responsive-img" style="width: 100px;
						height: 100px; object-fit: cover;" src="<?=base_url()?>assets/img/profiles/profile.jpg" >

					</center>
				</div>
				<div class="row" style="text-align: justify;">
					<h5 class="">Engr. David Flores</h5>
					<blockquote class="color-primary-green">
						<h5 class="color-black">1st Placer 2017 CE Board Exam</h5>
					</blockquote>
					<p>Hisham, 21, a graduate from Quirino High School, emerged No. 1 among the 2,514 board passers nationwide. His excellent academic performance has enabled him to get a full-academic scholarship from FEU Tech. </p>
					<a href="www.feutech.edu.ph"><i> - https://www.feutech.edu.ph</i></a>
				</div>
			</div>
		</div>
		<div class="col s2"></div>
	</div>
	
	<!--====  End of Engineers Section  ====-->
	
	
	
</div>

<!--====  End of Mobile Only Section  ====-->


<!--======================================
=            Web Only Section            =
=======================================-->

<div class="row hide-on-med-and-down">

<!--======================================
=            Banner Slideshow            =
=======================================-->
<div class="row" style="height: 100%;">
	<div id="a-div-slider" class="slider" style="position: relative; z-index: 0;">
		<ul class="slides">
			<li>
				<!-- <img src="https://lorempixel.com/580/250/nature/1"> -->
				<img src="<?=base_url()?>assets/img/slides/slide-5.jpg" style="filter: blur(2px);"> 
				<div  class="caption left-align a-nikki1">
					<h3 >Sharpen your skills</h3>
					<div class="col s8">
						<h5 class="light grey-text text-lighten-3 a-nikki2">If you are looking to sharpen or improve your skills, doing it online is the simplest way to do it. You’ll complete a series of rigorous courses, topics, and subjects that are related to any engineering programs. It’s not easy to find time in your busy schedule for review. But you know you need a review to effectively sharpen your skills.
						</h5>
					</div>
				</div>
			</li>
			<li>
				<img src="<?=base_url()?>assets/img/slides/slide-2.jpeg" style="filter: blur(2px);"> 
				<!-- <img src="https://lorempixel.com/580/250/nature/2"> -->
				<!-- <img src="<?=base_url()?>assets/img/2.png" >  -->
				<div class="caption left-align a-nikki1">
					<h3>Achieve your Goal</h3>
					<div class="col s8">
						<h5 class="light grey-text text-lighten-3 a-nikki2">With such a focus on performance measurement and accountability. Paying attention to the needs of engineering students will help them determine their learning and development strategy that will lead them to achieving their goals.
						</h5>
					</div>
				</div>
			</li>
			<li>
				<img src="<?=base_url()?>assets/img/slides/slide-3.jpg" > 
				<!-- <img src="<?=base_url()?>assets/img/3.png" >  -->

			</li>
			<li>
				<img src="<?=base_url()?>assets/img/slides/slide-4.jpg" > 
				<!-- <img src="<?=base_url()?>assets/img/4.png" > -->
			</li>
			<li>
				<img src="<?=base_url()?>assets/img/slides/slide-6.jpg" > 
				<!-- <img src="<?=base_url()?>assets/img/5.png" > -->
			</li>
		</ul>
	</div>

</div>

<!--====  End of Banner Slideshow  ====-->

<!--===============================
=            Schedules            =
================================-->


<div class="row" id="nav_schedule_sec">

	<div class="row">
		<center><i class="material-icons small color-primary-green">clear_all</i></center>
		<div class="col s12">
			<h4 class="center a-roboto-cond center">Correl Class Schedules</h4>

			<div class="col s4"></div>
			<div class="col s4">
				
				<select id="sections">
					<option value="" disabled selected>Choose Section</option>
					<?php 
					$sections = $this->Crud_model->fetch("offering");
					?>
					<?php foreach ($sections as $key => $value): ?>
						<option value="<?=$value->offering_id?>"><?=$value->offering_name?></option>

					<?php endforeach ?>
				</select>
				<label>Materialize Select</label>

			</div>
			<div class="col s4"></div>
		</div>
		
	</div>
	
	<!--======================================
	=            SCHEDULE SECTION            =
	=======================================-->
	
	<div class="row">

		<div class="col s12">
			<div class="timetable" id="schedule_section"></div>
		</div>
	</div>
	
	<!--====  End of SCHEDULE SECTION  ====-->
	
	
</div>


<!--====  End of Schedules  ====-->

<!--==============================
=            Features            =
===============================-->

<div class="row" id="nav_features_sec">
	<div class="row">
		<center><i class="material-icons small color-primary-green">clear_all</i></center>
		<h4 class="center a-roboto-cond">Features</h4>
	</div>
	<div class="row">
		<div class="col s12">
			<div class="col s3">	
				<center>
					<img src="<?=base_url()?>assets/img/icons/learning.svg" class="a-icons-landing" style="width: 50%;" alt="">
					<h5 class="a-icons-header center a-nikki1">Learn Online</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					E-Rev has an online learning management system that gets you the training you need. Because it's online, delivered over the web, you can proceed at your own pace, anytime, anywhere, and on any device.
				</p>
			</div>	
			<div class="col s3">
				<center>
					<img src="<?=base_url()?>assets/img/icons/personalized.svg" class="a-icons-landing" style="width: 50%;" alt="">
					<h5 class="a-icons-header center a-nikki1">Personalized Experience</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					Simulate a personalization engine by manually combing and interpreting the data from your learning management system (LMS) reports and making recommendations to your learning students.
				</p>
			</div>
			<div class="col s3">
				<center>
					<img src="<?=base_url()?>assets/img/icons/analytics.svg" class="a-icons-landing" style="width: 50%;" alt="">
					<h5 class="a-icons-header center a-nikki1">Grades Analysis</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					Online grade assessment is a powerful method to engage students, encourage learning and test student understanding of subject content. The LMS offers a wide variety of features to support an assessment of students.
				</p>
			</div>
			<div class="col s3">
				<center>
					<img src="<?=base_url()?>assets/img/icons/monitor.svg" class="a-icons-landing" style="width: 50%;" alt="">
					<h5 class="a-icons-header center a-nikki1">Lecturer Monitoring</h5>
				</center>
				<p class="a-icons-description a-nikki3">
					The timekeeping system will monitor the lecturer’s attendance. The time in and time out of lecturers will be recorded via the biometric scanner. The total number of hours rendered by the lecturers will be computed and generated by the system.
				</p>. 
			</div>
		</div>
	</div>
</div>

<!--====  End of Features  ====-->

<!--=============================================
=            What you'll get section            =
==============================================-->

<div class="row" id="nav_benefits_sec">
	<center><i class="material-icons small color-primary-green">clear_all</i></center>
	<h4 class="center a-roboto-cond" style="text-transform: uppercase;">What you'll get as a student</h4>
	<div class="row valign-wrapper" style="margin-top: 2%;">
		<div class="col s6">
			<center>
				<img src="<?=base_url()?>assets/img/icons/tailored.svg " style="width: 50%;">
			</center>
		</div>
		<div class="col s6">
			<h2 style="text-transform: capitalize;">Tailored experience, especially made for your needs</h2>
			<p class="a-icons-description a-nikki3">
				Our ethos centers on creating a great partnership with you to understand your engineering subjects as well as review and preparation for your board exam. That means we can tailor your LMS to get the right results.
			</p>
		</div>
	</div>
	<div class="row valign-wrapper">
		<div class="col s6">
			<h2 style="text-transform: capitalize;">enhance your skills and knowledge</h2>
			<p class="a-icons-description a-nikki3">
			Understanding skills and competencies. A student can complete a gap analysis evaluation that will determine where they lack the skills and competencies necessary to perform in their particular courses. Once a students' skill gaps have been determined, this data can be leveraged to help compose personalized learning modules that will fill those knowledge gaps and increase the employee’s skills, knowledge and ultimately, their performance.</p>
		</div>
		<div class="col s6">
			<center>
				<img src="<?=base_url()?>assets/img/icons/brain.svg " style="width: 50%;">
			</center>
		</div>
	</div>
	<div class="row valign-wrapper">
		<div class="col s6">
			<center>
				<img src="<?=base_url()?>assets/img/icons/megaphone.svg " style="width: 50%;">
			</center>
		</div>
		<div class="col s6">
			<h2 style="text-transform: capitalize;">Easy Access to Learning</h2>
			<p class="a-icons-description a-nikki3">
			We understand the need to have access to important resources such as modules and practice exams—anytime, anywhere, on virtually any device. E-Rev is compatible with all major browsers and Android devices so you always have real-time access to your system, regardless of your location or existing technology. </p>
		</div>
	</div>
</div>


<!--====  End of What you'll get section  ====-->


<!--=======================================
=            ENGINEERS Section            =
========================================-->


<div class="row" id="nav_statements_sec">
	<div class="col s2"></div>
	<div class="col s8 ">
		<h4>
			<center>
				<i class="material-icons small color-primary-green">clear_all</i>
				<p style="text-transform: uppercase;">FEU - Tech engineering students</p>
			</center>
		</h4>
		<!-- Hisham -->
		<div class="row valign-wrapper">
			<div class="col s5 ">
				<div class="col s6"></div>
				<div class="col s6 ">
					<img  class="circle responsive-img right" style="width: 100px;
					height: 100px; object-fit: cover;" src="<?=base_url()?>assets/img/profiles/hisham.jpg" >

				</div>
			</div>
			<div class="col s7">
				<h5 class="">Engr. Hisham Sacar</h5>
				<blockquote class="color-primary-green">
					<h5 class="color-black">1st Placer 2017 CE Board Exam</h5>
				</blockquote>
				<p>Hisham, 21, a graduate from Quirino High School, emerged No. 1 among the 2,514 board passers nationwide. His excellent academic performance has enabled him to get a full-academic scholarship from FEU Tech. </p>
				<a href="www.feutech.edu.ph"><i> - https://www.feutech.edu.ph</i></a>
			</div>
		</div>
		<!-- David Flores -->
		<div class="row valign-wrapper">
			<div class="col s5 ">
				<div class="col s6"></div>
				<div class="col s6 ">
					<img  class="circle responsive-img right" style="width: 100px;
					height: 100px; object-fit: cover;" src="<?=base_url()?>assets/img/profiles/david.jpg" >

				</div>
			</div>
			<div class="col s7">
				<h5 class="">Engr. David Flores</h5>
				<blockquote class="color-primary-green">
					<h5 class="color-black">2nd Placer 2017 CE Board Exam</h5>
				</blockquote>
				<p>Hisham, 21, a graduate from Quirino High School, emerged No. 1 among the 2,514 board passers nationwide. His excellent academic performance has enabled him to get a full-academic scholarship from FEU Tech. </p>
				<a href="www.feutech.edu.ph"><i> - https://www.feutech.edu.ph</i></a>
			</div>
		</div>
		
		<div class="row valign-wrapper">
			<div class="col s5 ">
				<div class="col s6"></div>
				<div class="col s6 ">
					<img  class="circle responsive-img right" style="width: 100px;
					height: 100px; object-fit: cover;" src="<?=base_url()?>assets/img/profiles/kenneth.jpg" >

				</div>
			</div>
			<div class="col s7">
				<h5 class="">Engr. Danielle Kenneth A. Tuzon</h5>
				<blockquote class="color-primary-green">
					<h5 class="color-black">10th place in the November 2017 Civil Engineering Board Exams</h5>
				</blockquote>
				<p>Continue embodying FEU's core value of excellence and the legacy of our institution in the field of Engineering! We are proud of you, iTamaraw!</p>
				<a href="www.feutech.edu.ph"><i> - https://www.feutech.edu.ph</i></a>
			</div>
		</div>
		
		
	</div>
	<div class="col s2"></div>
</div>



<!--====  End of ENGINEERS Section  ====-->

<div class="row " id="login_sec" style="height: 70vh;
background: url('<?=base_url()?>assets/img/background-user.jpg');
background-size: cover; background-repeat: no-repeat;
padding-bottom: 0 !important;
margin-bottom: 0 !important;">
<h4 id="nav_login_sec" class="center" style="text-transform: uppercase; padding-top: 4%;"> 
	<span style="border-bottom: 3px solid #F2A900;"> Start enhancing your skills</span>
</h4>
<center><a href="#"><button class="btn bg-primary-green waves-effect btn-large modal-trigger"
	data-target="a-login-modal">login</button></a></center>
</div>

</div>


<!--====  End of Web Only Section  ====-->




<!--=================================
=            Modal Login            =
==================================-->
<div id="a-login-modal" class="modal bg-color-white" >
	<center>
		<img src="<?=base_url()?>assets/img/feu-header.png" style="width: 50vh; margin-top: 1%;">
	</center>
	
	<hr>

	<div class="modal-content " style="padding: 0px !important;">
		<div class="row" >
			<div class="col s2"></div>
			<div class="col s8" >
				<blockquote class="color-primary-yellow">
					<h3 class="color-primary-green">LOGIN</h3>
					<p style="display: none" id="login-message">Invalid Account</p>
				</blockquote>
				<!--===================================
				=            Login Section            =
				====================================-->

				<div class="row ">
					<div class="input-field">
						<input id="login-username" autofocus="" type="text" class="validate ">
						<label for="login-username" class="color-primary-green">Username</label>
					</div>
				</div>
				<div class="row ">
					<div class="input-field">
						<input id="login-password" type="password" class="validate" >
						<label for="login-password" class="color-primary-green">Password</label>
					</div>
				</div>

				<!--====  End of Login Section  ====-->

				<button  onclick="login_verify();" class="waves-effect waves-light btn bg-primary-green right color-white">LOG IN</button>

				<a href="#!" class="modal-effect modal-close waves-effect waves-light btn red left color-white">Return</a>
			</div>
			<div class="col s2"></div>
		</div>
	</div>
	<div class="modal-footer bg-primary-green">
		<p class="center"> FEU - INSTITUTE OF TECHONOLOGY | &copy; 2017</p>
	</div>
</div>


<!--====  End of Modal Login  ====-->





<!--============================
=            FOOTER            =
=============================-->


<footer class="page-footer bg-primary-yellow color-black">
	<div class="container">
		<div class="row">
			<div class="col l6 s12">
				<h5 class="">P. PAREDES ST, SAMPALOC, MANILA</h5>
				<div >Icons made by 
					<a class="color-black a-Footer_Credits" href="http://www.freepik.com" title="Freepik">Freepik</a> 
					from 
					<a class="color-black a-Footer_Credits" href="https://www.flaticon.com/" title="Flaticon">www.flaticon.com</a>
					is licensed by
					<a class="color-black a-Footer_Credits" href="http://creativecommons.org/licenses/by/3.0/" title="Creative Commons BY 3.0" target="_blank">CC 3.0 BY</a>
				</div>
			</div>
			<div class="col l4 offset-l2 s12">
				<h5 class="">External Links</h5>
				<ul>
					<li><a class="color-black" href="#!">FEU - Institute of Technology</a></li>
				</ul>
			</div>
		</div>
	</div>
	<div class="footer-copyright">
		<div class="color-black">
			© 2017 FEU - Institute of Technology
		</div>
	</div>
</footer>


<!--====  End of FOOTER  ====-->



<!--============================
=            Script            =
=============================-->


<!--====  End of Script  ====-->